### PR TITLE
- Add Detection Engineering Weekly newsletter link, and 1 blog from the same blog site

### PR DESCRIPTION
**Pull request by zmallen**
I added two links here. The first link is my weekly newsletter dedicated to Detection Engineering content. I spend a good amount of time engaging the community and collecting links and resources for my job, so now I'm just sharing that aggregation!

The other link is to a blog I wrote about how Detection Engineering evolved into what it is today, and what we need to do going forward to make it succesful.

Cheers!

### CODE REVIEW

**Comment by zmallen** [comment]
Whoops, sorry for the long title. My github CLI put it inside the title instead of the body

**Comment by infosecB** [comment]
Thanks for your contribution, @zmallen!

**Comment by infosecB** [comment]
@zmallen just a heads up, your website appears to be unavailable. I have a script that removes links to content that is unavailable for > 30 days.

**Comment by zmallen** [comment]
Thanks, its substack so it should be up? Looks up from my end

**Comment by infosecB** [comment]
All good - looks like it was being block on my end as an NRD. I like what you’re doing with the blog!

**Pull request merged**
